image: gcc:8.3.0

before_script:
        # NOTE: cmake >= 3.16 is required by the currently bundled SDL source code, however the
        # gcc:8.3.0 image only has 3.13 available.
        #
        # Download and install a newer version of cmake:
        #
        - apt-get update && apt-get install -y curl
        - curl -LO https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz
        - tar -xzvf cmake-3.16.0-Linux-x86_64.tar.gz
        - export PATH=$(pwd)/cmake-3.16.0-Linux-x86_64/bin:$PATH
        - gcc --version
        - ldd --version
        - cmake --version

build-linux:
        stage: build
        script:
                - echo ${CI_COMMIT_TAG}
                - echo ${CI_COMMIT_SHA}
                - ./build-release.sh
                - ./run-tests.sh
                - mv build/target/ia ia_linux_x64_${CI_COMMIT_TAG}
        artifacts:
                paths:
                - ia_linux_x64_${CI_COMMIT_TAG}
                name: "ia_linux_x64_${CI_COMMIT_TAG}"
        only:
                - tags

build-windows:
        stage: build
        script:
                - echo ${CI_COMMIT_TAG}
                - echo ${CI_COMMIT_SHA}
                - apt-get update && apt-get install -y mingw-w64
                - ./build-release-windows-cross-compile.sh
                - mv build/target/ia ia_windows_x64_${CI_COMMIT_TAG}
        artifacts:
                paths:
                - ia_windows_x64_${CI_COMMIT_TAG}
                name: "ia_windows_x64_${CI_COMMIT_TAG}"
        only:
                - tags
