# Directory for saving user data, such as highscores and options.
#
# The game will try to find a writable directory for user data according to the
# following priority:
#
# 1) The path specified in this file, if not empty.
# 2) The directory retrieved by calling "SDL_GetPrefPath".
# 3) A "user_data" sub directory inside the game directory.
#
# NOTE: The '~' symbol or environment variables are NOT supported.
#
[paths]
user_data=
