#include "android_bootstrap.hpp"

#include <sys/stat.h>
#include <unistd.h>

#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "SDL.h"

namespace {

const char* const stamp_file_name = ".asset_manifest";

// Reads a file bundled in the APK (SDL_RWFromFile with a relative path routes
// through the Android AssetManager when the file isn't on disk).
bool read_asset(const std::string& name, std::vector<char>& out)
{
        SDL_RWops* rw = SDL_RWFromFile(name.c_str(), "rb");

        if (!rw) {
                return false;
        }

        const Sint64 size = SDL_RWsize(rw);

        if (size < 0) {
                SDL_RWclose(rw);

                return false;
        }

        out.resize((size_t)size);

        size_t total = 0;

        while (total < (size_t)size) {
                const size_t n =
                        SDL_RWread(rw, out.data() + total, 1, size - total);

                if (n == 0) {
                        break;
                }

                total += n;
        }

        SDL_RWclose(rw);

        return total == (size_t)size;
}

void make_parent_dirs(const std::string& path)
{
        for (size_t i = 0; i < path.size(); ++i) {
                if (path[i] == '/') {
                        mkdir(path.substr(0, i).c_str(), 0755);
                }
        }
}

std::string read_disk_file(const char* path)
{
        std::ifstream file(path, std::ios::binary);

        if (!file.is_open()) {
                return "";
        }

        std::ostringstream ss;

        ss << file.rdbuf();

        return ss.str();
}

bool write_disk_file(const std::string& path, const char* data, size_t size)
{
        std::ofstream file(path, std::ios::binary | std::ios::trunc);

        if (!file.is_open()) {
                return false;
        }

        file.write(data, (std::streamsize)size);

        return file.good();
}

}  // namespace

namespace android_bootstrap {

void init()
{
        const char* storage = SDL_AndroidGetInternalStoragePath();

        if (!storage) {
                SDL_Log("android_bootstrap: no internal storage path: %s",
                        SDL_GetError());

                return;
        }

        if (chdir(storage) != 0) {
                SDL_Log("android_bootstrap: chdir(%s) failed", storage);

                return;
        }

        // The manifest ("sha256  relative/path" per line, generated by the
        // gradle build) doubles as the extraction stamp: if the copy written
        // on a previous run matches the APK's, the data is already current.
        std::vector<char> manifest_data;

        if (!read_asset("asset_manifest.txt", manifest_data)) {
                SDL_Log("android_bootstrap: no asset manifest in APK");

                return;
        }

        const std::string manifest(manifest_data.begin(), manifest_data.end());

        if (read_disk_file(stamp_file_name) == manifest) {
                return;
        }

        SDL_Log("android_bootstrap: extracting game data to %s", storage);

        int nr_extracted = 0;
        int nr_failed = 0;

        std::istringstream ss(manifest);

        std::string line;

        while (std::getline(ss, line)) {
                const auto sep = line.find("  ");

                if (sep == std::string::npos) {
                        continue;
                }

                const std::string rel_path = line.substr(sep + 2);

                std::vector<char> data;

                if (!read_asset(rel_path, data)) {
                        SDL_Log("android_bootstrap: missing asset: %s",
                                rel_path.c_str());

                        ++nr_failed;

                        continue;
                }

                make_parent_dirs(rel_path);

                if (write_disk_file(rel_path, data.data(), data.size())) {
                        ++nr_extracted;
                } else {
                        SDL_Log("android_bootstrap: failed writing: %s",
                                rel_path.c_str());

                        ++nr_failed;
                }
        }

        // Only stamp a fully successful extraction, so a partial one (e.g.
        // out of disk space) is retried on the next launch.
        if (nr_failed == 0) {
                write_disk_file(
                        stamp_file_name,
                        manifest.data(),
                        manifest.size());
        }

        SDL_Log("android_bootstrap: extracted %d files (%d failed)",
                nr_extracted,
                nr_failed);
}

}  // namespace android_bootstrap
