// =============================================================================
// Copyright 2011-2022 Martin Törnqvist <m.tornq@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
// =============================================================================

#include "audio_data.hpp"

#include <iterator>
#include <unordered_map>
#include <utility>

// -----------------------------------------------------------------------------
// Private
// -----------------------------------------------------------------------------
static const std::unordered_map<std::string, audio::SfxId> s_str_to_sfx_id_map = {
        // Sound effects
        {"SFX_DOG_SNARL", audio::SfxId::dog_snarl},
        {"SFX_HISS", audio::SfxId::hiss},
        {"SFX_ZOMBIE_GROWL", audio::SfxId::zombie_growl},
        {"SFX_GHOUL_GROWL", audio::SfxId::ghoul_growl},
        {"SFX_OOZE_GURGLE", audio::SfxId::ooze_gurgle},
        {"SFX_FLAPPING_WINGS", audio::SfxId::flapping_wings},
        {"SFX_APE", audio::SfxId::ape},
        {"SFX_ALCHEMY_RUMMAGE", audio::SfxId::alchemy_rummage},
        {"SFX_BOOKSHELF_RUMMAGE", audio::SfxId::bookshelf_rummage},
        {"SFX_CABINET_OPEN", audio::SfxId::cabinet_open},
        {"SFX_HIT_SMALL", audio::SfxId::hit_small},
        {"SFX_HIT_MEDIUM", audio::SfxId::hit_medium},
        {"SFX_HIT_HARD", audio::SfxId::hit_hard},
        {"SFX_HIT_SHARP", audio::SfxId::hit_sharp},
        {"SFX_HIT_WHIP_SCOURGE", audio::SfxId::hit_whip_scourge},
        {"SFX_HIT_CORPSE_BREAK", audio::SfxId::hit_corpse_break},
        {"SFX_MISS_LIGHT", audio::SfxId::miss_light},
        {"SFX_MISS_MEDIUM", audio::SfxId::miss_medium},
        {"SFX_MISS_HEAVY", audio::SfxId::miss_heavy},
        {"SFX_PISTOL_FIRE", audio::SfxId::pistol_fire},
        {"SFX_PISTOL_RELOAD", audio::SfxId::pistol_reload},
        {"SFX_REVOLVER_FIRE", audio::SfxId::revolver_fire},
        {"SFX_REVOLVER_SPIN", audio::SfxId::revolver_spin},
        {"SFX_RIFLE_FIRE", audio::SfxId::rifle_fire},
        {"SFX_RIFLE_REVOLVER_RELOAD", audio::SfxId::rifle_revolver_reload},
        {"SFX_SHOTGUN_SAWED_OFF_FIRE", audio::SfxId::shotgun_sawed_off_fire},
        {"SFX_SHOTGUN_PUMP_FIRE", audio::SfxId::shotgun_pump_fire},
        {"SFX_SHOTGUN_RELOAD", audio::SfxId::shotgun_reload},
        {"SFX_MACHINE_GUN_FIRE", audio::SfxId::machine_gun_fire},
        {"SFX_MACHINE_GUN_RELOAD", audio::SfxId::machine_gun_reload},
        {"SFX_MIGO_GUN", audio::SfxId::migo_gun},
        {"SFX_SPIKE_GUN", audio::SfxId::spike_gun},
        {"SFX_BITE", audio::SfxId::bite},
        {"SFX_METAL_CLANK", audio::SfxId::metal_clank},
        {"SFX_RICOCHET", audio::SfxId::ricochet},
        {"SFX_EXPLOSION", audio::SfxId::explosion},
        {"SFX_EXPLOSION_MOLOTOV", audio::SfxId::explosion_molotov},
        {"SFX_GAS", audio::SfxId::gas},
        {"SFX_DARKBOLT_IMPACT", audio::SfxId::darkbolt_impact},
        {"SFX_DARKBOLT_RELEASE", audio::SfxId::darkbolt_release},
        {"SFX_AZA_GAZE", audio::SfxId::aza_gaze},
        {"SFX_HORN", audio::SfxId::horn},
        {"SFX_DOOR_BANG", audio::SfxId::door_bang},
        {"SFX_DOOR_BANG_GATE", audio::SfxId::door_bang_gate},
        {"SFX_DOOR_BANG_METAL", audio::SfxId::door_bang_metal},
        {"SFX_DOOR_BREAK", audio::SfxId::door_break},
        {"SFX_DOOR_BREAK_GATE", audio::SfxId::door_break_gate},
        {"SFX_DOOR_CLOSE", audio::SfxId::door_close},
        {"SFX_DOOR_CLOSE_GATE", audio::SfxId::door_close_gate},
        {"SFX_DOOR_CLOSE_METAL", audio::SfxId::door_close_metal},
        {"SFX_DOOR_OPEN", audio::SfxId::door_open},
        {"SFX_DOOR_OPEN_GATE", audio::SfxId::door_open_gate},
        {"SFX_DOOR_OPEN_METAL", audio::SfxId::door_open_metal},
        {"SFX_TOMB_OPEN", audio::SfxId::tomb_open},
        {"SFX_FOUNTAIN_DRINK", audio::SfxId::fountain_drink},
        {"SFX_BOSS_VOICE1", audio::SfxId::boss_voice1},
        {"SFX_BOSS_VOICE2", audio::SfxId::boss_voice2},
        {"SFX_CHAINS", audio::SfxId::chains},
        {"SFX_CRYSTAL_KEY_DISABLE", audio::SfxId::crystal_key_disable},
        {"SFX_STATUE_CRASH", audio::SfxId::statue_crash},
        {"SFX_LEVER_PULL", audio::SfxId::lever_pull},
        {"SFX_MONOLITH", audio::SfxId::monolith},
        {"SFX_THUNDER", audio::SfxId::thunder},
        {"SFX_GONG", audio::SfxId::gong},
        {"SFX_MAGIC_TRAP_TRIGGER", audio::SfxId::magic_trap_trigger},
        {"SFX_MECHANICAL_TRAP_TRIGGER", audio::SfxId::mechanical_trap_trigger},
        {"SFX_WADE", audio::SfxId::wade},
        {"SFX_SWIM", audio::SfxId::swim},
        {"SFX_BACKPACK", audio::SfxId::backpack},
        {"SFX_PICKUP", audio::SfxId::pickup},
        {"SFX_ELECTRIC_LANTERN", audio::SfxId::electric_lantern},
        {"SFX_POTION_QUAFF", audio::SfxId::potion_quaff},
        {"SFX_STRANGE_DEVICE_ACTIVATE", audio::SfxId::strange_device_activate},
        {"SFX_STRANGE_DEVICE_DAMAGED", audio::SfxId::strange_device_damaged},
        {"SFX_SPELL_SHIELD_BREAK", audio::SfxId::spell_shield_break},
        {"SFX_INSANITY_RISING", audio::SfxId::insanity_rising},
        {"SFX_DEATH", audio::SfxId::death},
        {"SFX_MENU_BROWSE", audio::SfxId::menu_browse},
        {"SFX_MENU_SELECT", audio::SfxId::menu_select},

        // Ambient sounds
        {"AMB_001", audio::SfxId::amb_001},
        {"AMB_002", audio::SfxId::amb_002},
        {"AMB_003", audio::SfxId::amb_003},
        {"AMB_004", audio::SfxId::amb_004},
        {"AMB_005", audio::SfxId::amb_005},
        {"AMB_006", audio::SfxId::amb_006},
        {"AMB_007", audio::SfxId::amb_007},
        {"AMB_008", audio::SfxId::amb_008},
        {"AMB_009", audio::SfxId::amb_009},
        {"AMB_010", audio::SfxId::amb_010},
        {"AMB_011", audio::SfxId::amb_011},
        {"AMB_012", audio::SfxId::amb_012},
        {"AMB_013", audio::SfxId::amb_013},
        {"AMB_014", audio::SfxId::amb_014},
        {"AMB_015", audio::SfxId::amb_015},
        {"AMB_016", audio::SfxId::amb_016},
        {"AMB_017", audio::SfxId::amb_017},
        {"AMB_018", audio::SfxId::amb_018},
        {"AMB_019", audio::SfxId::amb_019},
        {"AMB_020", audio::SfxId::amb_020},
        {"AMB_021", audio::SfxId::amb_021},
        {"AMB_022", audio::SfxId::amb_022},
        {"AMB_023", audio::SfxId::amb_023},
        {"AMB_024", audio::SfxId::amb_024},
        {"AMB_025", audio::SfxId::amb_025},
        {"AMB_026", audio::SfxId::amb_026},
        {"AMB_027", audio::SfxId::amb_027},
        {"AMB_028", audio::SfxId::amb_028},
        {"AMB_029", audio::SfxId::amb_029},
        {"AMB_030", audio::SfxId::amb_030},
        {"AMB_031", audio::SfxId::amb_031},
        {"AMB_032", audio::SfxId::amb_032},
        {"AMB_035", audio::SfxId::amb_035},
        {"AMB_036", audio::SfxId::amb_036},
        {"AMB_037", audio::SfxId::amb_037},
        {"AMB_038", audio::SfxId::amb_038},
        {"AMB_039", audio::SfxId::amb_039},
        {"AMB_040", audio::SfxId::amb_040},
        {"AMB_041", audio::SfxId::amb_041},
        {"AMB_042", audio::SfxId::amb_042},
        {"AMB_043", audio::SfxId::amb_043},
        {"AMB_044", audio::SfxId::amb_044},
        {"AMB_045", audio::SfxId::amb_045},
        {"AMB_046", audio::SfxId::amb_046},
        {"AMB_047", audio::SfxId::amb_047},
        {"AMB_048", audio::SfxId::amb_048},
        {"AMB_049", audio::SfxId::amb_049},
        {"AMB_050", audio::SfxId::amb_050},
        {"AMB_051", audio::SfxId::amb_051},
        {"AMB_052", audio::SfxId::amb_052},
        {"AMB_053", audio::SfxId::amb_053},
        {"AMB_054", audio::SfxId::amb_054},
        {"AMB_055", audio::SfxId::amb_055},
};

static const std::unordered_map<audio::SfxId, std::string> s_sfx_id_to_str_map = {
        // Sound effects
        {audio::SfxId::dog_snarl, "sfx_dog_snarl.ogg"},
        {audio::SfxId::hiss, "sfx_hiss.ogg"},
        {audio::SfxId::zombie_growl, "sfx_zombie_growl.ogg"},
        {audio::SfxId::ghoul_growl, "sfx_ghoul_growl.ogg"},
        {audio::SfxId::ooze_gurgle, "sfx_ooze_gurgle.ogg"},
        {audio::SfxId::flapping_wings, "sfx_flapping_wings.ogg"},
        {audio::SfxId::ape, "sfx_ape.ogg"},
        {audio::SfxId::alchemy_rummage, "sfx_alchemy_rummage.ogg"},
        {audio::SfxId::bookshelf_rummage, "sfx_bookshelf_rummage.ogg"},
        {audio::SfxId::cabinet_open, "sfx_cabinet_open.ogg"},
        {audio::SfxId::hit_small, "sfx_hit_small.ogg"},
        {audio::SfxId::hit_medium, "sfx_hit_medium.ogg"},
        {audio::SfxId::hit_hard, "sfx_hit_hard.ogg"},
        {audio::SfxId::hit_sharp, "sfx_hit_sharp.ogg"},
        {audio::SfxId::hit_whip_scourge, "sfx_hit_whip_scourge.ogg"},
        {audio::SfxId::hit_corpse_break, "sfx_hit_corpse_break.ogg"},
        {audio::SfxId::miss_light, "sfx_miss_light.ogg"},
        {audio::SfxId::miss_medium, "sfx_miss_medium.ogg"},
        {audio::SfxId::miss_heavy, "sfx_miss_heavy.ogg"},
        {audio::SfxId::pistol_fire, "sfx_pistol_fire.ogg"},
        {audio::SfxId::pistol_reload, "sfx_pistol_reload.ogg"},
        {audio::SfxId::revolver_fire, "sfx_revolver_fire.ogg"},
        {audio::SfxId::revolver_spin, "sfx_revolver_spin.ogg"},
        {audio::SfxId::rifle_fire, "sfx_rifle_fire.ogg"},
        {audio::SfxId::rifle_revolver_reload, "sfx_rifle_revolver_reload.ogg"},
        {audio::SfxId::shotgun_sawed_off_fire, "sfx_shotgun_sawed_off_fire.ogg"},
        {audio::SfxId::shotgun_pump_fire, "sfx_shotgun_pump_fire.ogg"},
        {audio::SfxId::shotgun_reload, "sfx_shotgun_reload.ogg"},
        {audio::SfxId::machine_gun_fire, "sfx_machine_gun_fire.ogg"},
        {audio::SfxId::machine_gun_reload, "sfx_machine_gun_reload.ogg"},
        {audio::SfxId::migo_gun, "sfx_migo_gun.ogg"},
        {audio::SfxId::spike_gun, "sfx_spike_gun.ogg"},
        {audio::SfxId::bite, "sfx_bite.ogg"},
        {audio::SfxId::metal_clank, "sfx_metal_clank.ogg"},
        {audio::SfxId::ricochet, "sfx_ricochet.ogg"},
        {audio::SfxId::explosion, "sfx_explosion.ogg"},
        {audio::SfxId::explosion_molotov, "sfx_explosion_molotov.ogg"},
        {audio::SfxId::gas, "sfx_gas.ogg"},
        {audio::SfxId::darkbolt_impact, "sfx_darkbolt_impact.ogg"},
        {audio::SfxId::darkbolt_release, "sfx_darkbolt_release.ogg"},
        {audio::SfxId::aza_gaze, "sfx_aza_gaze.ogg"},
        {audio::SfxId::horn, "sfx_horn.ogg"},
        {audio::SfxId::door_bang, "sfx_door_bang.ogg"},
        {audio::SfxId::door_bang_gate, "sfx_door_bang_gate.ogg"},
        {audio::SfxId::door_bang_metal, "sfx_door_bang_metal.ogg"},
        {audio::SfxId::door_break, "sfx_door_break.ogg"},
        {audio::SfxId::door_break_gate, "sfx_door_break_gate.ogg"},
        {audio::SfxId::door_close, "sfx_door_close.ogg"},
        {audio::SfxId::door_close_gate, "sfx_door_close_gate.ogg"},
        {audio::SfxId::door_close_metal, "sfx_door_close_metal.ogg"},
        {audio::SfxId::door_open, "sfx_door_open.ogg"},
        {audio::SfxId::door_open_gate, "sfx_door_open_gate.ogg"},
        {audio::SfxId::door_open_metal, "sfx_door_open_metal.ogg"},
        {audio::SfxId::tomb_open, "sfx_tomb_open.ogg"},
        {audio::SfxId::fountain_drink, "sfx_fountain_drink.ogg"},
        {audio::SfxId::boss_voice1, "sfx_boss_voice1.ogg"},
        {audio::SfxId::boss_voice2, "sfx_boss_voice2.ogg"},
        {audio::SfxId::crystal_key_disable, "sfx_crystal_key_disable.ogg"},
        {audio::SfxId::chains, "sfx_chains.ogg"},
        {audio::SfxId::statue_crash, "sfx_statue_crash.ogg"},
        {audio::SfxId::lever_pull, "sfx_lever_pull.ogg"},
        {audio::SfxId::monolith, "sfx_monolith.ogg"},
        {audio::SfxId::thunder, "sfx_thunder.ogg"},
        {audio::SfxId::gong, "sfx_gong.ogg"},
        {audio::SfxId::magic_trap_trigger, "sfx_magic_trap_trigger.ogg"},
        {audio::SfxId::mechanical_trap_trigger, "sfx_mechanical_trap_trigger.ogg"},
        {audio::SfxId::wade, "sfx_wade.ogg"},
        {audio::SfxId::swim, "sfx_swim.ogg"},
        {audio::SfxId::backpack, "sfx_backpack.ogg"},
        {audio::SfxId::pickup, "sfx_pickup.ogg"},
        {audio::SfxId::electric_lantern, "sfx_electric_lantern.ogg"},
        {audio::SfxId::potion_quaff, "sfx_potion_quaff.ogg"},
        {audio::SfxId::strange_device_activate, "sfx_strange_device_activate.ogg"},
        {audio::SfxId::strange_device_damaged, "sfx_strange_device_damaged.ogg"},
        {audio::SfxId::spell_shield_break, "sfx_spell_shield_break.ogg"},
        {audio::SfxId::insanity_rising, "sfx_insanity_rising.ogg"},
        {audio::SfxId::death, "sfx_death.ogg"},
        {audio::SfxId::menu_browse, "sfx_menu_browse.ogg"},
        {audio::SfxId::menu_select, "sfx_menu_select.ogg"},

        {audio::SfxId::AMB_START, ""},

        // Ambient sounds
        {audio::SfxId::amb_001, "amb_001.ogg"},
        {audio::SfxId::amb_002, "amb_002.ogg"},
        {audio::SfxId::amb_003, "amb_003.ogg"},
        {audio::SfxId::amb_004, "amb_004.ogg"},
        {audio::SfxId::amb_005, "amb_005.ogg"},
        {audio::SfxId::amb_006, "amb_006.ogg"},
        {audio::SfxId::amb_007, "amb_007.ogg"},
        {audio::SfxId::amb_008, "amb_008.ogg"},
        {audio::SfxId::amb_009, "amb_009.ogg"},
        {audio::SfxId::amb_010, "amb_010.ogg"},
        {audio::SfxId::amb_011, "amb_011.ogg"},
        {audio::SfxId::amb_012, "amb_012.ogg"},
        {audio::SfxId::amb_013, "amb_013.ogg"},
        {audio::SfxId::amb_014, "amb_014.ogg"},
        {audio::SfxId::amb_015, "amb_015.ogg"},
        {audio::SfxId::amb_016, "amb_016.ogg"},
        {audio::SfxId::amb_017, "amb_017.ogg"},
        {audio::SfxId::amb_018, "amb_018.ogg"},
        {audio::SfxId::amb_019, "amb_019.ogg"},
        {audio::SfxId::amb_020, "amb_020.ogg"},
        {audio::SfxId::amb_021, "amb_021.ogg"},
        {audio::SfxId::amb_022, "amb_022.ogg"},
        {audio::SfxId::amb_023, "amb_023.ogg"},
        {audio::SfxId::amb_024, "amb_024.ogg"},
        {audio::SfxId::amb_025, "amb_025.ogg"},
        {audio::SfxId::amb_026, "amb_026.ogg"},
        {audio::SfxId::amb_027, "amb_027.ogg"},
        {audio::SfxId::amb_028, "amb_028.ogg"},
        {audio::SfxId::amb_029, "amb_029.ogg"},
        {audio::SfxId::amb_030, "amb_030.ogg"},
        {audio::SfxId::amb_031, "amb_031.ogg"},
        {audio::SfxId::amb_032, "amb_032.ogg"},
        {audio::SfxId::amb_035, "amb_035.ogg"},
        {audio::SfxId::amb_036, "amb_036.ogg"},
        {audio::SfxId::amb_037, "amb_037.ogg"},
        {audio::SfxId::amb_038, "amb_038.ogg"},
        {audio::SfxId::amb_039, "amb_039.ogg"},
        {audio::SfxId::amb_040, "amb_040.ogg"},
        {audio::SfxId::amb_041, "amb_041.ogg"},
        {audio::SfxId::amb_042, "amb_042.ogg"},
        {audio::SfxId::amb_043, "amb_043.ogg"},
        {audio::SfxId::amb_044, "amb_044.ogg"},
        {audio::SfxId::amb_045, "amb_045.ogg"},
        {audio::SfxId::amb_046, "amb_046.ogg"},
        {audio::SfxId::amb_047, "amb_047.ogg"},
        {audio::SfxId::amb_048, "amb_048.ogg"},
        {audio::SfxId::amb_049, "amb_049.ogg"},
        {audio::SfxId::amb_050, "amb_050.ogg"},
        {audio::SfxId::amb_051, "amb_051.ogg"},
        {audio::SfxId::amb_052, "amb_052.ogg"},
        {audio::SfxId::amb_053, "amb_053.ogg"},
        {audio::SfxId::amb_054, "amb_054.ogg"},
        {audio::SfxId::amb_055, "amb_055.ogg"},
};

// -----------------------------------------------------------------------------
// audio
// -----------------------------------------------------------------------------
namespace audio
{
SfxId str_to_sfx_id(const std::string& str)
{
        const auto result = s_str_to_sfx_id_map.find(str);

        if (result == std::end(s_str_to_sfx_id_map)) {
                return SfxId::END;
        }
        else {
                return result->second;
        }
}

std::string sfx_id_to_filename(SfxId id)
{
        const auto result = s_sfx_id_to_str_map.find(id);

        if (result == std::end(s_sfx_id_to_str_map)) {
                return {};
        }
        else {
                return result->second;
        }
}

}  // namespace audio
