set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

# TODO: Disable as many unneeded features as possible.

set(SDL2IMAGE_AVIF OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_BMP OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_GIF OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_JPG OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_JXL OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_LBM OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_PCX OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_PNG ON CACHE BOOL "" FORCE)
set(SDL2IMAGE_PNM OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_QOI OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_SVG OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_TGA OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_TIF OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_WEBP OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_XCF OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_XPM OFF CACHE BOOL "" FORCE)
set(SDL2IMAGE_XV OFF CACHE BOOL "" FORCE)

set(SDL2MIXER_OPUS OFF CACHE BOOL "" FORCE)
set(SDL2MIXER_MOD_XMP OFF CACHE BOOL "" FORCE)
set(SDL2MIXER_MOD OFF CACHE BOOL "" FORCE)
set(SDL2MIXER_MIDI_FLUIDSYNTH OFF CACHE BOOL "" FORCE)
set(SDL2MIXER_WAVPACK OFF CACHE BOOL "" FORCE)

set(SDL_PATH SDL/src/SDL2-2.30.9)
set(SDL_IMAGE_PATH SDL/src/SDL2_image-2.8.2)
set(SDL_MIXER_PATH SDL/src/SDL2_mixer-2.8.0)

add_subdirectory(${SDL_PATH})
add_subdirectory(${SDL_IMAGE_PATH})
add_subdirectory(${SDL_MIXER_PATH})

set(SDL_LIBRARIES
        SDL2::SDL2-static
        SDL2_image::SDL2_image-static
        SDL2_mixer::SDL2_mixer-static
        )

target_link_libraries(ia        ${SDL_LIBRARIES})
target_link_libraries(ia-debug  ${SDL_LIBRARIES})

target_include_directories(
        ia-test
        PUBLIC
        ${SDL_PATH}/include
        ${SDL_IMAGE_PATH}/include
        ${SDL_MIXER_PATH}/include)

# TODO: Copy license files
# configure_file(${SDL_PATH}/LICENSE.txt          LICENSE-SDL.txt         COPYONLY)
# configure_file(${SDL_IMAGE_PATH}/LICENSE.txt    LICENSE-SDL_image.txt   COPYONLY)
# configure_file(${SDL_MIXER_PATH}/LICENSE.txt    LICENSE-SDL_mixer.txt   COPYONLY)

# install(FILES ${SDL_DISTR_FILES} DESTINATION ia)
# install(FILES ${SDL_DISTR_FILES} DESTINATION ia-debug)
